name: App
description: Short explanation / purpose etc.


service MultiQueue:
    in queue in-queue:
        max-length: 10000
    out queue:
        # - TaskTestReceiver.queue


service SlmpClient Ied15:
    cycle: 50 ms
    subscribe: /App/MultiQueue
    send-to: /App/MultiQueue.in-queue
    description: 'SLMP-IED-01.01'
    ip: '192.168.15.161'
    port: 4999
    diagnosis:                          # internal diagnosis
        point Status:                   # Ok(0) / Invalid(10)
            type: 'Int'
            # history: r
        point Connection:               # Ok(0) / Invalid(10)
            type: 'Int'
            # history: r
    db db_test_data:
        device-code: D
        offset: 1500
        size: 40
        point Platform.Heave:
            type: Real
            address:
                offset: 0
            comment: 'Heave height, m'
        point Platform.Roll:
            type: Real
            address:
                offset: 4
            comment: 'Roll angle, degrees'
        point Platform.Pitch:
            type: Real
            address:
                offset: 8
            comment: 'Pitch angle, degrees'
        point Platform.Yaw:
            type: Real
            address:
                offset: 12
            comment: 'Yaw angle, degrees'
        point Platform.DeltaAngleX:
            type: Real
            address:
                offset: 16
            comment: 'Rotation aroud X delta, degrees/s - 1'
        point Platform.DeltaAngleY:
            type: Real
            address:
                offset: 20
            comment: 'Rotation aroud Y delta, degrees/s - 1'
        point Platform.DeltaAngleZ:
            type: Real
            address:
                offset: 24
            comment: 'Rotation aroud Z delta, degrees/s - 1'
        point UnknownSignal:
            type: Real
            address:
                offset: 28
            comment: 'Unknown'
        point Platform.FluctuationPeriod:
            type: Real
            address:
                offset: 32
            comment: 'Period time of single fluctuation, s'
        point Platform.VelocityZ:
            type: Real
            address:
                offset: 36
            comment: 'Velocity of the platform on Z axis, m/s'


service TcpServer:
    reconnect: 1 s      # default 3 s
    address: 127.0.0.1:16678
    auth-secret:       # auth: none / auth-secret: pass: ... / auth-ssh: path: ...
        pass: '12345'
    in queue link:
        max-length: 10000
    out queue: /App/MultiQueue.in-queue
    # cache: /App/MainCache
